# Generated by Django 4.0.4 on 2022-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, editable=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
