# Generated by Django 4.0.4 on 2022-05-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('fullname', models.CharField(max_length=400)),
                ('CNIC', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DemoTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('file', models.BinaryField(blank=True, editable=True, null=True)),
            ],
        ),
       
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('services', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('fullname', models.CharField(max_length=400)),
                ('CNIC', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('ranking', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('fullname', models.CharField(max_length=400)),
                ('CNIC', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('badge', models.BooleanField(default=False)),
            ],
        ),
         migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('ord_start_time', models.DateTimeField(auto_now_add=True)),
                ('ord_end_time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('Orderprice', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quiz', models.BinaryField(blank=True, editable=True, null=True)),
                ('assesment', models.BinaryField(blank=True, editable=True, null=True)),
                ('lecture', models.BinaryField(blank=True, editable=True, null=True)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.orders')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.demotests')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=450)),
                ('description', models.TextField()),
                ('file', models.BinaryField(blank=True, editable=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
            ],
        ),
       
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.IntegerField(default=2)),
                ('name', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('image', models.BinaryField(blank=True, editable=True, null=True)),
                ('Startingprice', models.IntegerField(default=300)),
                ('review', models.ManyToManyField(to='TutorApp.reviews')),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.subjects')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='GigPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ManyToManyField(to='TutorApp.gigs')),
                ('package', models.ManyToManyField(to='TutorApp.packages')),
            ],
        ),
        migrations.CreateModel(
            name='CodeEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.teachers')),
            ],
        ),
    ]
