# Generated by Django 4.0.4 on 2022-05-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_adminmodel_demotests_orders_packages_payment_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='review',
        ),
        migrations.AddField(
            model_name='reviews',
            name='gig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.gigs'),
        ),
        migrations.CreateModel(
            name='GigRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutorApp.gigs')),
            ],
        ),
    ]
