# Generated by Django 4.0.4 on 2022-05-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0003_remove_gigs_review_reviews_gig_gigrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigpackages',
            name='package',
        ),
        migrations.AddField(
            model_name='gigpackages',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.packages'),
        ),
    ]
