# Generated by Django 4.0.4 on 2022-05-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0004_remove_gigpackages_package_gigpackages_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigrating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
