# Generated by Django 4.0.4 on 2022-05-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0005_alter_gigrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='TutorApp.teachers'),
        ),
    ]
