# Generated by Django 4.0.4 on 2022-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0005_remove_codeeditor_student_remove_codeeditor_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
